name: CI

on:
  push:
    branches: main
    paths:
      - 'vite.config.ts'
      - 'package.json'
      - 'src/**'
      - 'public/**'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  draft_release:
    permissions:
      contents: write # Allows this job to create releases

    strategy:
      fail-fast: true
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

      - name: Get package version
        id: version
        # uses: ashley-taylor/read-json-property-action@v1.0
        # with:
        #   path: ./package.json
        #   property: version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build # ${{ steps.version.outputs.value }}
        run: |
          pnpm run build
          cd dist
          zip -r ../v${VERSION}.zip *

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: v${VERSION}
          files: v${VERSION}.zip
