# 测试繁体中文支持情况
name: Chinese Traditional

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
            version: 8

      - uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'pnpm'
      
      - run: |
          pnpm install
          node scripts/cn.js
        
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.os }}
          path: scripts/
          retention-days: 1